server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crud  # 여기서 'crud'는 데이터베이스의 이름입니다.
    username: root
    password: a1234
    driver-class-name: org.mariadb.jdbc.Driver

